name: workout_tracker
description: Eine App zum Verfolgen deiner Workouts

publish_to: 'none' # Do not publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.20.2
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/exercise_database.json