name: workout_tracker
description: Eine App zum Verfolgen deiner Workouts

publish_to: 'none' # Do not publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.0
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/exercise_database.json